[package]
name = "stable-hash"
version = "0.3.0"
edition = "2018"


[dependencies]
blake3 = "0.3.3"
num-traits = "0.2.11"
leb128 = "0.2.4"
num-bigint = "0.2.6"
lazy_static = "1.4.0"

[dev-dependencies]
twox-hash = "1.5.0"
hex = "0.4.2"